[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for wayland"
authors = ["poly000"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
