[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for wayland"
authors = ["poly000"]
license-file = "LICENSE"

default-run = "waylyrics"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# configuration
toml = "0.7.3"
serde = { version = "1.0", features = ["derive"] }

# lyric parse
lrc-nom = "0.1.1"

# ui
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_8", "v4_10"] }
ncmapi = {git = "https://github.com/poly000/ncmapi-rs", branch = "into_raw_data"}
tokio = { version = "1", features = ["rt-multi-thread"] }
