[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for wayland"
authors = ["poly000"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# configuration
toml = "0.7.3"
serde = { version = "1.0", features = ["derive"] }

# lyric parse
lrc-nom = "0.1.1"

# lyric get
reqwest = { version = "0.11.16", features = ["blocking"] }

# ui
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_8", "v4_10"] }
