[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for wayland"
authors = ["poly000"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
lrc = "0.1.7"
lrc-nom = "0.1.1"
reqwest = { version = "0.11.16", features = ["blocking"] }

[dependencies.fltk]
version = "^1.4"
features = ["use-wayland"]
