name: FOSSA Dependency scan
on: push

jobs:
  dependency-scan:
    name: dependency-scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo apt-get install libssl-dev libgtk-4-dev libdbus-1-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: |
          export WAYLYRICS_DEFAULT_CONFIG=
          export WAYLYRICS_THEME_PRESETS_DIR=
          cargo +nightly build --release --all-features
      - name: Install fossa-cli from github
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
      - name: Run FOSSA dependency scan
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          fossa analyze .
