name: test

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  WAYLYRICS_THEME_PRESETS_DIR: /usr/share/waylyrics/themes

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libgtk-4-dev libdbus-1-dev pkg-config weston
    - uses: Swatinem/rust-cache@v2
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build --release
    - name: Installation
      run: |
        sudo mkdir -p /usr/share/waylyrics
        sudo install -m644 io.poly000.waylyrics.gschema.xml /usr/share/glib-2.0/schemas/
        sudo install -dm755 ${WAYLYRICS_THEME_PRESETS_DIR}
        sudo cp -r themes/* ${WAYLYRICS_THEME_PRESETS_DIR}/

        # install schema
        sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
    - name: Start waylyrics
      run: |
        # init weston
        weston --backend=headless-backend.so -Swayland-1 &
        # let weston prepare for 1s
        sleep 1
        # set config so waylyrics try to initialize QQMusic provider
        mkdir -p ~/.config/waylyrics
        echo 'qqmusic-api-base-url = "http://127.0.0.1:3300"' > ~/.config/waylyrics/config.toml
        # start waylyrics
        ret=-1
        WAYLAND_DISPLAY=wayland-1 RUST_BACKTRACE=1 timeout 5s ./target/release/waylyrics || ret=$?
        if [ $ret -eq 124 ]; then
          echo "waylyrics survived the smoke test"
          exit 0
        else
          echo "waylyrics crashed during the smoke test (exit code $ret)"
          exit 1
        fi
    - name: Prepare assets
      shell: bash
      run: |
        tar -cvzf amd64-linux-gnu.tar.gz target/release/waylyrics \
        LICENSE res io.poly000.waylyrics.gschema.xml
        
    - name: Declare some variables # https://stackoverflow.com/a/61699863
      id: vars
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v3
      with:
        name: linux-x86_64
        path: amd64-linux-gnu.tar.gz
